"""
IPO Analysis Module for Arthaprama.

This module provides comprehensive analytical tools for evaluating Indian IPOs,
including growth metrics, risk assessment, valuation analysis, and composite scoring.
"""

from arthaprama.ipo.growth import (
    GrowthCalculationError,
    calculate_all_growth_metrics,
    cfo_growth,
    ebitda_growth_yoy,
    ebitda_margin,
    eps_growth_yoy,
    pat_cagr_3yr,
    pat_margin,
    profit_growth_yoy,
    revenue_cagr_3yr,
    revenue_growth_yoy,
    roce,
    roe,
)
from arthaprama.ipo.risk import (
    RiskCalculationError,
    calculate_all_risk_metrics,
    cfo_to_debt,
    cfo_to_pat,
    contingent_liabilities_to_nw,
    current_ratio,
    customer_concentration,
    debt_to_equity,
    fcf_to_pat,
    free_cash_flow,
    interest_coverage,
    net_debt,
    net_debt_to_ebitda,
    promoter_pledge_ratio,
    quick_ratio,
)
from arthaprama.ipo.scoring import (
    ScoreBreakdown,
    generate_ipo_score,
)
from arthaprama.ipo.valuation import (
    ValuationCalculationError,
    calculate_all_valuation_metrics,
    earnings_yield,
    enterprise_value,
    ev_ebitda_premium_vs_peer,
    ev_to_ebitda,
    ev_to_sales,
    ipo_dilution,
    pb_ratio,
    pe_premium_vs_peer,
    pe_ratio,
    peg_ratio,
    post_ipo_eps,
    price_to_fcf,
    ps_ratio,
)
from arthaprama.ipo.workflow import (
    FullIPOAnalysisResult,
    GrowthAnalysisResult,
    IPOWorkflowEngine,
    IPOWorkflowError,
    RiskAnalysisResult,
    ValuationAnalysisResult,
    run_full_ipo_analysis,
)

__all__ = [
    # Workflow
    "FullIPOAnalysisResult",
    "GrowthAnalysisResult",
    # Growth
    "GrowthCalculationError",
    "IPOWorkflowEngine",
    "IPOWorkflowError",
    "RiskAnalysisResult",
    # Risk
    "RiskCalculationError",
    # Scoring
    "ScoreBreakdown",
    "ValuationAnalysisResult",
    # Valuation
    "ValuationCalculationError",
    "calculate_all_growth_metrics",
    "calculate_all_risk_metrics",
    "calculate_all_valuation_metrics",
    "cfo_growth",
    "cfo_to_debt",
    "cfo_to_pat",
    "contingent_liabilities_to_nw",
    "current_ratio",
    "customer_concentration",
    "debt_to_equity",
    "earnings_yield",
    "ebitda_growth_yoy",
    "ebitda_margin",
    "enterprise_value",
    "eps_growth_yoy",
    "ev_ebitda_premium_vs_peer",
    "ev_to_ebitda",
    "ev_to_sales",
    "fcf_to_pat",
    "free_cash_flow",
    "generate_ipo_score",
    "interest_coverage",
    "ipo_dilution",
    "net_debt",
    "net_debt_to_ebitda",
    "pat_cagr_3yr",
    "pat_margin",
    "pb_ratio",
    "pe_premium_vs_peer",
    "pe_ratio",
    "peg_ratio",
    "post_ipo_eps",
    "price_to_fcf",
    "profit_growth_yoy",
    "promoter_pledge_ratio",
    "ps_ratio",
    "quick_ratio",
    "revenue_cagr_3yr",
    "revenue_growth_yoy",
    "roce",
    "roe",
    "run_full_ipo_analysis",
]
